name: Playwright Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run Cucumber + Playwright tests headless
      - name: Run tests
        run: npx cucumber-js --require-module ts-node/register --require src/stepDefinitions/**/*.ts --require src/support/**/*.ts
